services:
  database:
    image: mysql:latest
    container_name: mysql-db
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_MY_PASSWORD}
      - DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_MAPPED_PORT}:${MYSQL_LOCAL_PORT}
    volumes:
      - db:/var/lib/mysql
  
  back-end:
    depends_on:
      - database
    build: ./Back-end
    container_name: backEnd_c
    env_file:
      - ./.env
    environment:
      - DB_HOST=database
      - DB_USER=${MYSQL_MY_USER}
      - DB_PASSWORD=${MYSQL_MY_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=${MYSQL_LOCAL_PORT}
      - APP_PORT=${NODE_PORT}
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - ./Back-end:/app

volumes:
  db:
